### ISSUE TITLE
Pihole crashes / stops to work

### ISSUE THREAD

**Issue by lucatortiglione** [pi-hole/FTL#1017]
Hi,
my Pihole still crashes / stops to work even with posix_fallocate_return patch.

You should be able to download the logs here

https://www.dropbox.com/s/r55ef9q7l5qt9bs/pihole-FTL.7z?dl=0

**Comment by DL6ER** [comment]
I downloaded and looked at the file, you can remove it.
Since the log contains more than one million lines and I wasn't able to find a single occurrence of the usual things like:

- `warning`
- `fatal`
- `crash`

I need some more info from you here. How does the stopping manifest itself?

---

What may be related is that I do see almost 10,000 lines like
```
[2021-01-07 09:41:14.244 3136/F720] **** got reply error is REFUSED (nowhere to forward to) (ID 891415,  [...])
```

which points to an error outside of Pi-hole. Could you show us what was logged in `pihole.log` for this query?
Use
```
grep -A10 ": 891415 " /var/log/pihole.log
```
to get this.

It'd also be helpful if you could generate and upload a debug log using `pihole -d` (agree to upload and share the URL so we can access it). This will contains a small dump of parts of your Pi-hole configuration (you'll see on the screen what we'll see as well) so it should reduce ping-pong question/answering here.

**Comment by lucatortiglione** [comment]
Bad configuration on the smartphone
