### ISSUE TITLE
new API timestamps should be doubles

### ISSUE THREAD

**Issue by 0x0a11c0de** [pi-hole/FTL#1051]
[The timestamps in the new API are integers](https://github.com/pi-hole/FTL/blob/7608dd5c8dcb11f902311abe032c7ccdb3766ba5/src/api/docs/content/specs/history.yaml#L211). Many queries can happen within a second, which can't be differentiated with integer timestamps. Double timestamps give microsecond precision so these queries can be differentiated.

**Comment by DL6ER** [comment]
Thanks for your suggestion. So far, they are integers because this is the convention for [Unix time](https://en.wikipedia.org/wiki/Unix_time). Consequently, the return value of `time()` is of integer type as well. Sub-second accuracy was never needed (and never requested before). In fact, we ensure that they results returned by the API are always in order, however, I do see some value in returning timestamps with sub-second accuracy. As we don't use them internally anywhere, there is also no possible floating point comparison problem.

We already add log lines with millisecond accuracy. I'll check if there is anything problematic about this tomorrow.

**Comment by DL6ER** [comment]
This has been implemented by 4dc2ddc4.

**Comment by 0x0a11c0de** [comment]
Awesome! Just a note based on the commit message: even though the input supports nanoseconds, a double can only hold unix time to microseconds. The reason is a double can only represent ~16 digits. Whole seconds of unix time currently takes up 10 digits, which leaves 6 digits for the fractional seconds. This is why you'll always see precise time broken up into two fields, typically an int type for the whole seconds and either an int type or a double for the fractional seconds.

**Comment by DL6ER** [comment]
Sure, hence the "up to" ;-)
