### ISSUE TITLE
err_name_not_resolved

### ISSUE THREAD

**Issue by yoelalvarez** [pi-hole/FTL#1079]
### Versions

- Pi-hole:  5.4.2
- AdminLTE:  5.4
- FTL:  5.7

### Platform

- OS and version:  Ubuntu 18.04

- Platform:  VM

### Expected behavior

Load site

### Actual behavior / bug

Getting error: err_name_not_resolved
Page loads after reloading several times

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
