### ISSUE TITLE
pihole-FTL.db accessed once per second

### ISSUE THREAD

**Issue by h88e22dgpeps56sg** [pi-hole/FTL#1157]
### Versions
Pi-hole version is v5.3.1 (Latest: v5.3.1)
AdminLTE version is v5.5.1 (Latest: v5.5.1)
FTL version is v5.8.1 (Latest: v5.8.1)

### Platform
- OS and version:  Debian 10.10
- Platform:  Raspberry Pi 2 B

### Expected behavior

`pihole-FTL.db` is accessed every `DBINTERVAL` minutes by `pihole-FTL`.

### Actual behavior / bug

`pihole-FTL.db` is accessed once every second.

### Steps to reproduce

0. have Pi-hole running
1. execute `fatrace -tC pihole-FTL`
2. see access

## Debug Token

- [✓] Your debug token is: https://tricorder.pi-hole.net/FfoX0hqs/

### Screenshots

https://lutim.ggc-project.de/YhUfWThu.png

### Additional context

- `iotop` does not recognize any actual writes or reads.
- In `top` you can even see the CPU time accumulating slowly, even if there is no DNS request whatsoever. 
- `DBINTERVAL` setting doesn't matter
- In fatrace ORCW is Open, Read, Close, Write.
- I don't know if there are other tools, but for fatrace you need version >= 0.14. On Debian 10 you need to compile it yourself:
1. `curl -sSL "https://github.com/martinpitt/fatrace/archive/refs/tags/0.16.3.tar.gz" > 0.16.3.tar.gz`
2. `tar -xvzf "0.16.3.tar.gz"`
3. `cd fatrace-0.16.3/`
4. `make`
5. `./fatrace -tC pihole-FTL`

**Comment by DL6ER** [comment]
Yes, this is expected and because the source code of the database thread is along the lines of
``` c
while(true)
{
  dbopen();
  if(wantA())
    doA();
  if(wantB())
    doB();
  if(wantC())
    doC();
  // ...
  dbclose();
  sleep(1000); // 1 second
}
```

It is done like this to avoid having to open the database in possibly a lot of places. However, I do see that the total number of database open/closeing will be reduced when doing it like
``` c
if(wantA())
{
  dbopen();
  doA();
  dbclose();
}
if(wantB())
{
  dbopen();
  doB();
  dbclose();
}
// ...
```

I would like to avoid using intermediate variables and do an `if(wantedA || wantedB || wantedC){ ... }` because the actual code is somewhat more complicated (even if not too much):

https://github.com/pi-hole/FTL/blob/b90ab8b1e78d7aece11c8fee1c3c00817761de52/src/database/database-thread.c#L41-L148

I'm not sure what your conclusion was above (I guess there was none). You reported the database being open-/closed every second without `iotop` recognizing anything. I wouldn't want to change this just for changing it as everything is working very well at the moment and I don't think this causes any actual writes. However. I'd be open for changing this if it is turn out to be useful for anything.

Thoughts?

**Comment by h88e22dgpeps56sg** [comment]
Thanks a lot for you detailed answer.
Changing this would decrease CPU usage by a bit – it's not much, but it accumulates over time. Also it would improve the overall design of the function. It may sound far-fetched, but this question should make it more clear: Why open the database if you don't want anything in there? – Don't do unnecessary things. Something like this came to my mind:
```
while(true)
{
  sqlite3 *db = NULL;
  if(wantA())
    dbopenifnotyetopen();
    doA();
  if(wantB())
    dbopenifnotyetopen();
    doB();
  // …
  dbclose(); // this already checks for "NULL"
  sleep(1000); // 1 second
}
```
Your suggestion sounds good, too:
```
if(wantA())
{
  dbopen();
  doA();
  dbclose();
}
// …
```

**Comment by DL6ER** [comment]
I don't know if you have joined [our currently running beta testing](https://pi-hole.net/2021/07/04/pi-hole-ftl-v5-9-web-v5-6-and-core-v5-4-beta-testing/#page-content), but if you did you may want to try out the new branch [`tweak/database_access`](https://github.com/pi-hole/FTL/tree/tweak/database_access) where I added the suggested improvement to the database thread.
You can check out the modified FTL version with the simple command
```
pihole checkout ftl tweak/database_access
```

While looking at the `fatrace` output, I found another spot where disk I/O can be reduced by ensuring two `UPDATE` SQL commands are run still within a running transaction instead of after. This causes the journal file to be created/destroyed only one (instead of two) times every `DBINTERVAL`.

I also noticed `fatrace` is not extremely accurate when it comes to recording file access/writing. I enabled heavy logging in FTL which causes hundreds of lines per second into the log file. However, `fatrace` showed less than five `CWO` accesses to the log file. Reading and writing to both the database files seems to be recorded more accurately. Whatever this may mean. The log file is opened and closed every time so it ~~cannot~~ shouldn't be buffered writes causing actual disk I/O to happen less often.

**Comment by h88e22dgpeps56sg** [comment]
Your effort is greatly appreciated. :)

I changed to beta resp. tweak branch. Everything seems to run smoothly so far. I also ran a quick measurement with 15 minutes each, no incoming DNS queries and no DB access:
```
Pi-hole version is release/v5.4
AdminLTE version is release/v5.6
FTL version is release/v5.9
```
CPU time in `top`: 0:00.57

```
Pi-hole version is release/v5.4
AdminLTE version is release/v5.6
FTL version is tweak/database_access
```
CPU time in `top`: 0:00.21

**Comment by DL6ER** [comment]
The next version of FTL has been released. Please update and run
```
pihole checkout master
```
to get back on-track. The feature branch you switched to will not receive any further updates.

Thanks for helping us to make Pi-hole better for us all!

If you have any issues, please either reopen this ticket or (preferably) create a new ticket describing the issues in further detail and only reference this ticket. This will help us to help you best.
