### ISSUE TITLE
Pihole DNS returns 127.0.1.1 when querying its FQDN (e.g. hostname.lan)

### ISSUE THREAD

**Issue by SpikeTheMarmot** [pi-hole/FTL#1168]
### Versions
- Pi-hole version is v5.4 (Latest: v5.4)
- AdminLTE version is v5.6 (Latest: v5.6)
- FTL version is v5.9 (Latest: v5.9)

### Platform
- OS and version:  Debian 10.10
- Platform: Raspberry Pi

### Expected behavior
Pihole returns its private network IP address, e.g. `192.168.178.5`, when the FQDN, e.g. `raspi.lan` is queried.
(I use `lan` as the domain name in the DHCP settings)

### Actual behavior / bug
```
spike@pc: drill raspi
;; QUESTION SECTION:
;; raspi.	IN	A
;; ANSWER SECTION:
raspi.	2	IN	A	192.168.178.5

spike@pc: drill raspi.lan
;; QUESTION SECTION:
;; raspi.lan.	IN	A
;; ANSWER SECTION:
raspi.lan.	2	IN	A	127.0.1.1
```

### Additional context
The problem occurs since the new FTL version (v5.9). I believe it's because of the change how `pi.hole` and the hostname are handled by FTL (https://github.com/pi-hole/FTL/pull/1111). Maybe I'm wrong.

Contents of `/etc/hosts`:
```
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       raspi
```
The content of this file has not changed. It was working before the update.
I know I could use `REPLY_ADDR4` or change the hosts file to avoid this issue, but I think that is only hiding the underlying problem and I shouldn't need to do that.
If this is, contrary to my expectation, intentional, what's the best way to fix this issue?

**Comment by DL6ER** [comment]
This is an interesting issue, thanks for bringing it up. The PR you mentioned added special rules for `pi.hole` and the hostname. We forgot to add special handling for `<hostname>.<local domain>` or `<pi.hole>.<local_domain>`
I'll add those for the next release.

This issue did not happen before, because `dnsmasq` added the local domain internally when `expand-hosts` is enabled (the default). Sorry for that. We're preparing a small bugfix release for a few minor things and I'll make sure to include this fix for what you observe here.

**Comment by DL6ER** [comment]
@SpikeTheMarmot Would you mind trying if
```
pihole checkout ftl tweak/domain_suffix
```
fixes the issue for you?

Please try it as if nothing has happened otherwise (remove `REPLY_ADDR4` or any possible `hosts` edits).

**Comment by SpikeTheMarmot** [comment]
@DL6ER Thanks for your fast reply and bug fix.
The changes in `tweak/domain_suffix` do solve the issue for me.
