### ISSUE TITLE
Pi-hole does not listen on other interfaces (WireGuard)

### ISSUE THREAD

**Issue by Mic-Pod** [pi-hole/FTL#1207]
Hi,
Before recent updates clients connected via WireGuard were able to resolve queries. Currently client are not getting answers from Pi-Hole when they are connected remotely using WireGuard interface.

- When `Interface listening behavior` is set to `Listen only on interface eno1` the devices connected locally are getting answers, but those clients connected remotely are not (previously it was working fine).
- When `Interface listening behavior` is set to `Listen on all interfaces` no one is getting answers, not even clients connected locally

### Versions
- Pi-hole: 5.5
- AdminLTE: 5.7
- FTL: 5.10.2

### Platform
- OS and version: Ubuntu Server 18.04.6 LTS
- Platform: x86 (Intel NUC)

### Expected behavior

Clients connected via WireGuard can resolve DNS queries.

### Actual behavior / bug

Clients connected via WireGuard are not getting answers from Pi-hole

**Comment by Mic-Pod** [comment]
> Please post a debug token.

https://tricorder.pi-hole.net/91B7hVlo/

**Comment by yubiuser** [comment]
It seems you have issues connecting to an non-Pi-hole upstream server. Are you blocking port 53?

```
*** [ DIAGNOSING ]: Operating system
[i] dig return code:  9
[i] dig response:  ;; connection timed out; no servers could be reached
[✗] Distro:  Ubuntu
[✗] Error: Ubuntu is not a supported distro (https://docs.pi-hole.net/main/prerequisites/)

*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✓] safe.oferta-payment.quest is 0.0.0.0 on lo (127.0.0.1)
[✓] safe.oferta-payment.quest is 0.0.0.0 on eno1 (10.0.0.201)
[✗] Failed to resolve safe.oferta-payment.quest on wg0 (10.1.0.1)
[✗] Failed to resolve safe.oferta-payment.quest on wg1 (10.2.0.1)
[✗] Failed to resolve doubleclick.com via a remote, public DNS server (8.8.8.8)


    PIHOLE_INTERFACE=eno1
    IPV4_ADDRESS=10.0.0.201/24
    DNSMASQ_LISTENING=single
```

Can you generate a debug log with `Listen on all interfaces` enabled?

Do you see the queries from the `wg` interfaces in your query log?

**Comment by DL6ER** [comment]
> Log with `Listen on all interfaces` enabled

![Screenshot from 2021-10-09 10-25-57](https://user-images.githubusercontent.com/16748619/136650584-c00ff571-84bd-4b94-bf54-2684714c6c88.png)

Tricorder log from before (listen only on `eno1`):

![Screenshot from 2021-10-09 10-26-48](https://user-images.githubusercontent.com/16748619/136650604-9068a9a0-9200-431b-a9e2-dda9a29144e8.png)

To me, both look as expected for the given option. I don't know why `wg1` doesn't work but it may be down or there are firewall rules preventing DNS lookups to work.

---

I don't think `DEBUG_NETWORKING` is of any use here, it is for debugging where the automatically determined address for replying to `pi.hole` comes from. Also, the option `Listen only on interface eno1` should do exactly this and when remote clients worked before, then this was broken (even when I don't recall any change in this direction for years).

You may have seen the restriction to the "Listen on all interfaces" option:
> Allows only queries from devices that are at most one hop away (local devices)

Maybe the kernel decides that your clients are more than one hop away somehow, I don't know if you have any other speical networking in place (like VLANs, etc.). I'd suggest trying the third option "Listen on all interfaces, permit all origins" because this removes any restrictions on the maximum allowed "distance" of clients.

**Comment by Mic-Pod** [comment]
OK, thank You for explaining and confirming this. So I guess, like You wrote earlier, it was working before although it shouldn't.
