### ISSUE TITLE
Network Information not visible

### ISSUE THREAD

**Issue by Rude-Boy** [pi-hole/FTL#1239]
### Versions
Pi-hole version is v5.6 (Latest: v5.6)
AdminLTE version is v5.8 (Latest: v5.8)
FTL version is v5.11 (Latest: v5.11)

### Platform
- OS and version:  Raspian
- Platform:  Raspberry Pi Zero W

### Expected behavior
when i open `http://192.168.X.Y/admin/settings.php` I expect to see the IPv4 and IPv6 addresses
like here:
https://www.dominicjordan.com/wp-content/uploads/2019/05/PiHole-System-Settings.png
"Network Information" on the left; "FTL Information" on the right

### Actual behavior / bug

"Network Information" are not visible. There is only "FTL Information"

### Steps to reproduce

open `http://192.168.X.Y/admin/settings.php` (logged in as Admin)

## Debug Token

- URL:  https://tricorder.pi-hole.net/6ax5eYi2/

### Screenshots

https://imgur.com/a/ptV80B6

### Additional context

-

**Comment by jfb-pihole** [comment]
This was removed intentionally, since the information was not reliable. It was sourced from setupVars.conf which was updated only if users run pihole -r. If network information changed in the mean time (which can happen quite often especially with IPv6) the file and the web interface displayed outdated information.

https://github.com/pi-hole/AdminLTE/commit/cf917a6391a6a309be9dfdf87f0bde7c66d698b4

**Comment by Rude-Boy** [comment]
I see, thank you.
it's not as easy as before, but I can get the information in the terminal running `ip addr`
