### ISSUE TITLE
Clients are not recognized correctly

### ISSUE THREAD

**Issue by bluemanos** [pi-hole/FTL#1260]
### Versions

  - Pi-hole version is v5.7 (Latest: v5.7)
  - AdminLTE version is v5.9 (Latest: v5.9)
  - FTL version is v5.12 (Latest: v5.12)

### Platform
- OS and version:  Debian 10 Buster
- Platform: PC

### Expected behavior

_Clients will be correctly recognized._

### Actual behavior / bug

_Clients are not correctly recognized. I'm getting a few times a `xiaomi-ania` client name for different clients. This happening on Dashboard and as well on Query log. That doubled clients has different IP address._

## Debug Token

- URL:  https://tricorder.pi-hole.net/OKjx2Ny1/

### Screenshots

![image](https://user-images.githubusercontent.com/9991002/147277633-b44da74c-2e89-45b6-9242-139bd5613924.png)
![image](https://user-images.githubusercontent.com/9991002/147277411-82ad9809-8d3a-4c29-b79f-11ad616d00c6.png)

**Comment by DL6ER** [comment]
Whenever there is no name available, Pi-hole goes to the database of devices ever seen before and tries to defer a hostname.

I suspect an incorrect database entry for this client that is getting the wrong name. Please run
``` bash
sqlite3 "/etc/pihole/pihole-FTL.db" "SELECT * FROM network_addresses WHERE name = 'xiaomi-ania'"
```
on your Pi-hole.

**Comment by bluemanos** [comment]
@DL6ER yes, you are right.
```
 $ sqlite3 "/etc/pihole/pihole-FTL.db" "SELECT * FROM network_addresses WHERE name = 'xiaomi-ania'"
23|192.168.5.59|1640338021|xiaomi-ania|1640338021
8|192.168.5.254|1640338021|xiaomi-ania|1640296080
22|192.168.5.54|1640338021|xiaomi-ania|1640338021
18|192.168.5.57|1640338021|xiaomi-ania|1640338021
8|192.168.5.242|1640338021|xiaomi-ania|1640338021
4|192.168.5.243|1640338021|xiaomi-ania|1640338021
10|192.168.5.22|1640338021|xiaomi-ania|1640338021
```
How does it happen? I never named other devices (other IPs) with the name `xiaomi-ania`.

Can I delete all rows from that table with a `xiaomi-ania` name?

**Comment by bluemanos** [comment]
I deleted the entries from Tools > Network, and they appears once again for the same devices.

**Comment by DL6ER** [comment]
In your case, the `xiaomi-ania` had a number of different addresses:
- 192.168.5.59
- 192.168.5.254
- 192.168.5.54
- 192.168.5.57
- 192.168.5.242
- 192.168.5.243
- 192.168.5.22

and Pi-hole memorized the hostname for each of these addresses.

Looking at these IP addresses, it seems you are using a *non-deterministic* or *sequential* DHCP server. The problem with this is that the IP address of devices depends on the order of appearance in the network. After, e.g., a power failure, the IP addresses of the devices solely depend on the order of appearance of the devices in the network (which is almost random). In contrast, a *deterministic* DHCP server (such as the one embedded in Pi-hole) looks at the MAC of a device and tries to find a unique address it can hand out to this device.

First, I'd suggest deleting all the lines as you tried, but need to stop FTL while doing so. Otherwise, FTL will simply re-add what it knows to the database, as you have seen.

```
sudo service pihole-FTL stop
sudo sqlite3 /etc/pihole/pihole-FTL.db "DELETE FROM network_addresses WHERE name = 'xiaomi-ania'"
sudo service pihole-FTL start
```

Now you have a few options:

1. Try to switch your router to *deterministic* DHCP lease mode. If this is not possible, you could consider moving the DHCP server from your router over to your Pi-hole. I'm using exactly this setup for over five years at home and I'm very happy with it.
2. If you do not want to do this, consider using *conditional forwarding*. This works by sending hostname queries for devices within your local network to a forward destination of your choosing. Typically, this will be the router. This way, you do not need to maintain the `custom.list` in addition to the static assignments on your router and keep both lists in sync.
3. If you also don't want this, you can at least set the option [`NAMES_FROM_NETDB=false`](https://docs.pi-hole.net/ftldns/configfile/#names_from_netdb) in `/etc/pihole/pihole-FTL.conf`. This will stop FTL from trying to defer hostnames using previous addresses stored in the database. The client would in this case only show up as unresolved IP address.

And if you have any further questions, we are still here! Merry Christmas :christmas_tree:

**Comment by bluemanos** [comment]
@DL6ER Thank you for your comprehensive answer.
Option (3) is best for me, this is what I want to achieve - leave unresolved IP address if it is not added in Local DNS > DNS Records.

Thank you for your time and Merry Christmas to you!

**Comment by nikita-y** [comment]
I know the issue is closed but I'd like to leave it here nontheless. I've been having a similar issue when running docker in rootless mode. Hope this comment helps someone in troubleshooting.
