### ISSUE TITLE
Error in "create view queries": client_by_id.id should be client_by_id.ip

### ISSUE THREAD

**Issue by thomasmerz** [pi-hole/FTL#1301]
I think I found a bug in the new view "queries":

You are referencing column "id" from table "[client_by_id](https://docs.pi-hole.net/database/ftl/#client_by_id)" with column "client" from table [query_storage](https://docs.pi-hole.net/database/ftl/#query-table) to create "queries"-view:
https://github.com/pi-hole/FTL/blob/52e6b95858424671134b90efc46fea931f23e91e/src/database/query-table.c#L579

But given my current data from my database, this won't make any sense:
```
23:02 $ sudo sqlite3 ../pihole-FTL.db
SQLite version 3.36.0 2021-06-18 18:36:39
Enter ".help" for usage hints.
sqlite> select * from client_by_id where name like 'bi-iphon%';
2|192.168.42.203|bi-iphonese-north
24|192.168.42.117|bi-iphonese

sqlite> select * from query_storage where client like '192.168.42.203' limit 2;

sqlite> select * from query_storage where client like '192.168.42.117' limit 2;
10809149|1636349710|1|3|gsp85-ssl.ls.apple.com|192.168.42.117|||||
10809150|1636349710|16|2|gsp85-ssl.ls.apple.com|192.168.42.117|45.90.30.39#53||||

sqlite>
```
But WebGUI still shows queries for IP=192.168.42.203 which is bi-iphonese-north

<img width="381" alt="grafik" src="https://user-images.githubusercontent.com/18568381/154156407-e5748514-d3a4-43be-92e4-3f807824c6a7.png">

It should be `WHERE c.ip = q.client` instead of `WHERE c.id = q.client` because "id" is just a "counter" or ID of the entry. Do you agree?

**Comment by DL6ER** [comment]
What you see is correct. It is by design that that database may contain either an ID integer (new queries after the update) or an IP string (before the update). The `CASE` you're quoting takes care of this and seamlessly blends both cases for a uniform experience when querying the `queries` view.

This is a necessary compromise as rewriting the database to swap existing IPs ba their respective IDs would have taken too long (think in terms of hours to days) on low-end hardware like Raspberry Pi Model 1. The problem will auto-fix once your long-term data in the old format expires after one year (or a custom time if configured).

**Comment by thomasmerz** [comment]
After a second look I totally agree with @DL6ER and excuse for my brain-knot 😁 
Because I don't want to wait until my long-term data will have been expired in some months, I will update and swap existing IPs by their respective IDs manually due to no-low-end hardware.
