### ISSUE TITLE
FTL crashing on raspi zero 2 w

### ISSUE THREAD

**Issue by Prophet-Phoenix** [pi-hole/FTL#1311]
### Versions

- Pi-hole:  5.9
- AdminLTE:  5.11
- FTL:  5.14

### Platform

- OS and version:  raspberry pi os lite

- Platform:  raspi zero 2 w with usb ethernet nic

### Expected behavior

FTL not crashing

### Actual behavior / bug

FTL crashed, i noticed because i couldnt visit websites anymore. Admin panel showed "Ftl not running".

### Steps to reproduce

Unclear to me, since it ran fine for some time. (19+ days)

## Debug Token

- URL:  https://tricorder.pi-hole.net/ElmQtPwC/

### Additional context

tail -n 500 pihole-ftl.log > [report.txt](https://github.com/pi-hole/FTL/files/8190446/report.txt)

**Comment by DL6ER** [comment]
Sorry for the inconvenience you've experienced and also sorry for the delay of replying to you. This is the first time I've seen a bug report in this code region and, checking back with the code, I'm currently lacking an explanation for this else than possibly corrupted RAM memory caused by improper energy supply.

Dis this happen more than once? Can you somehow reproduce it?
If so, it'd be interesting if you could try setting `DEBUG_VECTORS=true` in `/etc/pihole/pihole-FTL.conf` (create the file if it does not exist). If you don't think this can be reproduced, then it may also not be the best option to add this debug setting as it will cause the log files to grow *significantly* (think in several orders of magnitude) and could easily grow too large for an average SD card size.

**Comment by Prophet-Phoenix** [comment]
I'm using an old usb charger, so first i will change that to a more reliable one. If the issue persits, i will set `debug_vectors` and report back.
