### ISSUE TITLE
sqlite3 errors in FTL.log (database schema has changed (17))

### ISSUE THREAD

**Issue by jpgpi250** [pi-hole/FTL#1422]
### Versions
  Pi-hole version is v5.12 (Latest: v5.12)
  AdminLTE version is v5.14.1 (Latest: v5.14.1)
  FTL version is v5.17 (Latest: v5.17)

### Platform
Linux raspberrypi 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/Linux

### Actual behavior / bug
sqlite3 errors in /var/log/pihole/FTL.log
```
[2022-09-04 07:24:56.652 795M] SQLite3 message: statement aborts at 37: [SELECT EXISTS(SELECT domain from vw_whitelist WHERE domain = ? AND group_id IN (0));] database schema has changed (17)
[2022-09-04 07:24:56.653 795M] SQLite3 message: statement aborts at 37: [SELECT EXISTS(SELECT domain from vw_blacklist WHERE domain = ? AND group_id IN (0));] database schema has changed (17)
[2022-09-04 07:24:56.654 795M] SQLite3 message: statement aborts at 45: [SELECT EXISTS(SELECT domain from vw_gravity WHERE domain = ? AND group_id IN (0));] database schema has changed (17)
```
**note that, until yesterday, I was running tweak/white_regex_id**
- there are no such entries in yesterdays log
- apparently the errors started appearing after the gravity run (sunday morning). my gravity runs at 01h29,, completed (log date) at 01h33, there are no errors in the gravity log. The first error (see above) appeared in the log at 02h29
- [FTL.zip](https://github.com/pi-hole/FTL/files/9484124/FTL.zip)

## Debug Token
- URL:  https://tricorder.pi-hole.net/NDOka4Bo/

**Comment by rdwebdesign** [comment]
I don't think there were any recent changes in these 3 views. 

Just a question:
This looks like just a warning. Do you see any "adverse effects"?

**Comment by yubiuser** [comment]
It's very likely due to testing the special branch.

**Comment by DL6ER** [comment]
> `database schema has changed`

I don't know when the last schema change was but not recently - also not in the special branch you've been testing before. How long was FTL master running before this happened? Did you do any manual interaction with the database within this time?

**Comment by jpgpi250** [comment]
@yubiuser, special branch....
might be possible, can' exclude this, but, why than didn't these errors appear immediately after the upgrade (no errors in yesterdays log, update was competed yesterday at noon? The errors started appearing after the weekly gravity update. A question might be: who is making these queries (FTL?) and why (what is the trigger / code).
@rdwebdesign, adverse effects...
It's very hard to tell if there are abnormal entries in the database / web interface, for example, I've just recently identified a CNAME problem, that probably is in there since the beginning of CNAME detection., see [here](https://discourse.pi-hole.net/t/cname-cant-explain-this/57457), issue [here](https://github.com/pi-hole/FTL/issues/1421). So, no, currently haven't identified a problem, due to these sqlite3 error messages, which doesn't mean there aren't any.

**Comment by DL6ER** [comment]
@jpgpi250 please check the schemas before (the database on the old SD card) and after (what you have right now) using
```
pihole-FTL sqlite3 /etc/pihole/gravity.db ".schema vw_whitelist"
```
and
```
pihole-FTL sqlite3 /etc/pihole/gravity.db ".schema domainlist"
```

**Comment by jpgpi250** [comment]
old SD card, with tweak/white_regex_id
new SD card, with fresh install latest version

insert old SD card, ran the commands, than new SD card, ran again:

![image](https://user-images.githubusercontent.com/24669386/188306709-0f2df285-dccc-4ef7-bad0-39b7fc11a84d.png)

**Comment by DL6ER** [comment]
If the schema has changed although it hasn't ... there aren't many options left. This is, in general, only a mild warning without any adverse effects. It is only printed because a previously prepared (as in: pre-compiled) query has to be compiled *again* due to *any* kind of change to any related table in the database. This will just take some extra microseconds of processing time. Not worth mentioning, usually, however, this process can be slow if you have very many and very complex SQL statements (both aren't true in our case).

One of the remaining reasons why this could show up here is any kind of manual database interaction. This does not only mean modification of the table at hand itself, it also means "any changes to the database structure" - basically everything else than just adding/updating removing rows. Like adding/removing/changing column definitions of *any* table or adding/removing other tables in the same file. Even running `VACUUM` on the database file (to reduce the file size) can cause this warning when the table (and its indices!) were re-written and, hence, the query needs to be re-compiled.

The only other remaining reason I can think of right now is: Have you tried branch [`[tweak/sqlite3_optimize](https://github.com/pi-hole/FTL/tree/tweak/sqlite3_optimize)`](https://github.com/pi-hole/FTL/pull/1385) at any point? This branch hasn't been merged into any regular (`development` or `master`) branch, however, it was there for trying. In case the optimization has gathered some data that could be used to "enhance" a given query, it will re-prepare the SQL statement leading to the same (now slightly misleading) warning message. This behavior is why the use of optimization may violate SQLite3's "Query Plan Stability guarantee" since it enables re-evaluation of the plan after the bindings are set based on the values of the parameters, and not merely based on the query itself, the schema, and the statistics.

**Comment by jpgpi250** [comment]
I've edited my previous comment (while yours wasn't visible to me yet (possible cause?)

> Have you tried branch [tweak/sqlite3_optimize](https://github.com/pi-hole/FTL/tree/tweak/sqlite3_optimize) (https://github.com/pi-hole/FTL/pull/1385) at any point?

No I haven't, I was testing tweak/white_regex_id for over 10 days, until the new pihole release became available.

> This warning database schema has changed would be printed by any action with prepared statements on a database after any change to its schema (incl. running VACUUM).

I run VACUUM on the databases, copied over from the old SD, prior to replacing the newly created (empty) databases. Of course, replacing them is done while pihole-FTL is stopped.
If VACUUM is causing this, you can close the issue.

**Comment by rdwebdesign** [comment]
Do you have any other applications reading or writing to the database, while FTL is running?
VACCUM is another possibility.

**Comment by jpgpi250** [comment]
@rdwebdesign: some scripts run (cron) to generate reports, of interest to me, read only!

As explained earlier, I run VACUUM on databases, copied over from old SD cards, when performing a fresh install (which I pretty much do every time a new version is released - automated)

I haven't seen any of the sql error messages any more after I initially opened the issue, have been switching branches during the day (other open issue, CNAME problem, now solved, thanks to the dedication of DL6ER).

If I don't see the error again during this week, I'll close the issue, probable cause: VACUUM.

**Comment by jpgpi250** [comment]
new SD + full install with db copied over from old SD (due to new raspbian release), no more errors in the log...
