### ISSUE TITLE
Error listening on Unix socket /run/pihole/FTL.sock: Cannot assign requested address (99)

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/FTL#1451]
### Versions
  Pi-hole version is development v5.12.2-43-g997a771d (Latest: v5.12.2)
  AdminLTE version is chartjs v5.15.1-30-g31e89ddc (Latest: v5.15.1)
  FTL version is development vDev-814db79 (Latest: v5.18.1)

FTL logs during each start

```
[2022-10-03 14:07:28.840 22108M] Error listening on Unix socket /run/pihole/FTL.sock: Cannot assign requested address (99)
```

However, the file exits and is writable to `pihole`user.

```
rockpi@rockpi-4b:~$ ls -lha /run/pihole/FTL.sock 
srwxrwxrwx 1 pihole pihole 0 Oct  3 14:08 /run/pihole/FTL.sock
```

**Comment by DL6ER** [comment]
Thanks for your report. There is a regression from https://github.com/pi-hole/FTL/pull/1396 that says the error comes from the socket file in all cases - even when this happens when trying bind to the IPv4/6 sockets.

Please try branch `fix/socket_warning` that fixes this warning and check if it is still reporting the socket file.

**Comment by yubiuser** [comment]
Fixed with https://github.com/pi-hole/FTL/releases/tag/v5.18.2
