### ISSUE TITLE
new feature - configurable number of top_domains

### ISSUE THREAD

**Issue by redlegoman** [pi-hole/FTL#147]
Hi, This is just to let you know that I have fiddled with your code to alter the number of domains reported from FTL when asking for "top-domains". This was so I could see a different number of the admin dashboard. At first I simply altered the "count" variable in request.c but then I changed it so I could set the number from setupVars.conf (it defaults to 10 if not set in setupVars.conf). 

I have read your contributors guide and see that you would prefer bug fixes rather than additional features, so I don't want to go through a long journey learning how to create a pull request etc. Basically I have no idea how to contribute to a github project and don't want to waste your (or my) time learning how to do it with your project if you would prefer I didn't. I wouldn't want to make more of a mess than help! You should probably also know that I am definitely an amateur programmer, but I've dabbled enough over the years to know how to use StackOverflow!

**Comment by DL6ER** [comment]
No worries! Thanks for your suggestion. However, I should tell you that what you are asking for is already implemented since quite some time as described also [here](https://github.com/pi-hole/FTL#implemented-keywords-starting-with--subject-to-change):
![screenshot at 2017-10-16 17-01-38](https://user-images.githubusercontent.com/16748619/31618976-b16b2bf6-b293-11e7-8c53-33dae43fb238.png)

You can pass this through the API using a numeric argument for `topItems`, e.g.
http://pi.hole/admin/api.php?topItems=15

**Comment by DL6ER** [comment]
Addendum: If you want to change it on the dashboard, you should modify it in the place which queries the data. See https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/js/index.js#L299

**Comment by redlegoman** [comment]
D'oh. Well there you go. I should have just asked! Sorry about that , and thanks.
