### ISSUE TITLE
PARSE_ARP_CACHE=false should not disable network table

### ISSUE THREAD

**Issue by onovy** [pi-hole/FTL#1533]
### Versions
  Pi-hole version is v5.15.5 (Latest: v5.15.5)
  AdminLTE version is v5.18.4 (Latest: v5.18.4)
  FTL version is v5.21 (Latest: v5.21)
  Container tag is: 2023.02.2

### Platform
- OS and version: Ubuntu
- Platform:  Docker

### Expected behavior
Setting PARSE_ARP_CACHE=false should only disable parsing of kernel's neighbor table (arp table).

### Actual behavior / bug
Setting PARSE_ARP_CACHE=false disables this whole function: https://github.com/pi-hole/FTL/blob/master/src/database/network-table.c#L1226

This function is responsible for:
* parse ARP table from kernel
* network_addresses table cleanup/expire
* saving client to DB known to FTL

PARSE_ARP_CACHE should enable/disable only "parse ARP table from kernel" but keep DB cleanup and saving already known clients from FTL to DB.

**Comment by DL6ER** [comment]
Thanks for your input and sorry for the large delay. I will check how the function can be restructured to achieve what you are suggesting. Out of pure curiosity: Why are you disabling ARP reading to begin with?

**Comment by onovy** [comment]
because I run Pi-hole in solo vlan and solo subnet inside Docker, thus ARP reading is completely useless for me :)

**Comment by DL6ER** [comment]
But it also won't harm :-) I'm just trying to remember why we added the option to disable this in the first place (and create correlated maintenance workload). Checking out the code, I think it's a better idea to just remove the option altogether? Reading an empty ARP cache (or one only containing the one device and possibly the (virtual) gateway seems fine as they *do* exist in the reality of your Pi-hole.

**Comment by DL6ER** [comment]
We are in the middle of developing the next-generation FTL v6.0 (actually "middle" is to be understood being much closer to the end rather than the beginning as we already have a working alpha for months). Hence, I added the enhancement addressing your points already over there (https://github.com/pi-hole/FTL/commit/d0e3500c4e6de35f2ca03007064d88d36e1c281c). I decided to not drop the option - for whatever reason we decided to add it in the first place.
