### ISSUE TITLE
Domain validation allows invalid characters

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/FTL#1760]
Domain input field allows to add invalid characters (e.g. `test&`, `test[`). 
Sometimes non-allowed characters cause an error to be reported, but adds strange domain to the database

Try with

`fsdf&??{{{`

results in

![Screenshot at 2023-11-15 13-19-36](https://github.com/pi-hole/web/assets/26622301/602cfc20-1810-4263-9d81-5a147ea2aa1d)

**Comment by DL6ER** [comment]
This should be fixed in the API to be consistent also with CLI, etc. interaction.

My initial idea would be reusing the already existing
https://github.com/pi-hole/FTL/blob/17716ef51a54384a21afc88562e271162575961a/src/tools/gravity-parseList.c#L43

used for determining if domains imported during `pihole -g` are valid. This function has extensively been tested with millions of domains.

**Comment by yubiuser** [comment]
Good idea to re-use that code.

**Comment by DL6ER** [comment]
One other remark on the strange `jQuery_3700..._17005...` string you have found:  `??` is used as a placeholder for the callback function when using [`JSONP`](https://en.wikipedia.org/wiki/JSONP).

There are two possible solutions:

1. Explicitly add `jsonp: false` in the `$.ajax` options
2. Explicitly set the content type to *not* be `jsonp`, e.g., `contentType: "application/json"`

See http://bugs.jquery.com/ticket/12326/

--> We need two PRs to fix this entirely (even when the FTL one alone will already prevent the domains from being added)
