### ISSUE TITLE
Top blocked domains should not return duplicates and sort descending

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/FTL#1812]
Not sure how I ended there, but this looks wrong

```
{
    "domains": [
        {
            "domain": "collector.github.com",
            "count": 132
        },
        {
            "domain": "mask.icloud.com",
            "count": 5
        },
        {
            "domain": "collector.github.com",
            "count": 132
        },
        {
            "domain": "collector.github.com",
            "count": 132
        },
        {
            "domain": "collector.github.com",
            "count": 132
        },
        {
            "domain": "collector.github.com",
            "count": 132
        },
        {
            "domain": "collector.github.com",
            "count": 132
        },
        {
            "domain": "collector.github.com",
            "count": 132
        },
        {
            "domain": "collector.github.com",
            "count": 132
        },
        {
            "domain": "collector.github.com",
            "count": 132
        }
    ],
    "total_queries": 4104,
    "blocked_queries": 137,
    "took": 0.0011808872222900391
}
```
![Screenshot at 2023-12-08 22-21-15](https://github.com/pi-hole/FTL/assets/26622301/4fdced5a-b50b-493a-8b3a-a7839e34c3e5)

**Comment by yubiuser** [comment]
Restating `FTL` fixed it.

**Comment by rdwebdesign** [comment]
Maybe this was caused by another branch test...

When you test different branches, are you using the same database or a total clean installation (or container)?

**Comment by yubiuser** [comment]
Same database. My v6 is running bare metal. If I delete the database every time I have no queries to play with.

**Comment by DL6ER** [comment]
Looking at this before I even opened the code is: Maybe there have only been two domains in your history. FTL first collects the domains and then sorts them by ID. So the result may have been `0,1` and the rest of the array was (by initialization) still at `0,0,0,0,0,0,0,0` leasing to what you are seeing here.

...

While looking at the code: That's only part of the answer. There is code to prevent exactly this, actually. However, this is kind-of a regression of #1694 because we can have recycled domains not being eligible for inclusion here but still counting towards the total number of records we can return.
