### ISSUE TITLE
Bug: "Network overview" -> “First seen” later than ”Last Query"

### ISSUE THREAD

**Issue by AS98765** [pi-hole/FTL#2021]
### Versions
- Pi-hole: v5.18.3
- AdminLTE: v5.25.2
- FTL: v5.21

### Platform
- OS and version: Raspberry Pi OS Lite (64-bit), Bookworm
- Platform: Raspberry Pi 

### Expected behavior

“First seen” earlier than ”Last Query” (at least according to my understanding)

### Actual behavior / bug

“First seen” later than ”Last Query"

### Steps to reproduce

Imo not necessary

### Debug Token

...

### Screenshots

![Screenshot 2024-07-30 124833 - m 2](https://github.com/user-attachments/assets/d4925425-727b-49ac-8dd3-a92c5f3d7460)

### Additional context

N/A

**Comment by DL6ER** [comment]
It is not rounded.

Example: Say a client makes its **first** and **only** query at `21:45:12` - the client is only added to the database on the next full minute `21:66:00` due to the 60 seconds interval noted by @yubiuser. The client's timestamp `firstSeen` in the database is actually the timestamp where it is added to the database, so `firstSeen` is to be interpreted as "first seen by the database" not "first seen by the DNS server". I agree that this is confusing. It can be changed here:

https://github.com/pi-hole/FTL/blob/8943e26041c8730a5a9060eb64f76c6c2dd4e458/src/database/network-table.c#L548-L566

In this example (which is - by pure coincidence - identical to @AS98765's screenshot btw), we have
- `now = 21:66:00` (interval triggered network table processing)
- `lastQuery = 21:45:12` (the real last query)

We could now change
``` diff
  // Bind now to prepared statement (2nd argument) 
- if((rc = sqlite3_bind_int(query_stmt, 2, now)) != SQLITE_OK) 
+ if((rc = sqlite3_bind_int(query_stmt, 2, lastQuery < now ? lastQuery : now)) != SQLITE_OK) 
```

but this would still not be the perfect solution as `lastQuery` might be later than the *real* `client->firstSeen` which isn't available in this function (yet!). I will work on the proper fix instead -it should be easy enough.
