### ISSUE TITLE
Pihole-FTL dnsmasq listen-address

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [pi-hole/FTL#243]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

7

---

**[BUG | ISSUE] Expected Behaviour:**
`listen-address=127.0.0.1`
`listen-address=192.168.x.x`

This config entries make dnsmasq/pihole-ftl only listen on those addresses.

**[BUG | ISSUE] Actual Behaviour:**
Dnsmasq/pihole-ftl listens on wildcard

`netstat -tulpen | grep pihole`:
`tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      110        1189900    27553/pihole-FTL`
`tcp        0      0 127.0.0.1:4711          0.0.0.0:*               LISTEN      110        1189252    27553/pihole-FTL`
`tcp6       0      0 :::53                   :::*                    LISTEN      110        1189902    27553/pihole-FTL`
`tcp6       0      0 ::1:4711                :::*                    LISTEN      110        1189254    27553/pihole-FTL`
`udp        0      0 0.0.0.0:53              0.0.0.0:*                           110        1189899    27553/pihole-FTL`
`udp6       0      0 :::53                   :::*`

**[BUG | ISSUE] Steps to reproduce:**

- Add listen-address to dnsmasq config
- Run `netstat -tulpen | grep pihole`

**Device specifics**

Hardware Type: RasPi 3b+
OS: Raspbian Lite

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
Are you on the FTLDNS beta? The only wildcard is on port 53. The others are all localhost bindings. This is due to how the embedded dnsmasq works. It will listen on those interfaces and IPs, but will only respond to the ones specified in the config.

**Comment by DL6ER** [comment]
@Unkn0wn-MDCLXIV We don't modify the binding routines of `dnsmasq`. Looking at `dnsmasq`'s source code. This seems to be the expected behavior. Instead of limiting the listener to only listen on specific interfaces, the code checks whether an incoming query was sent from something where it should listen to (the check is done in `iface_check()` in `network.c`). If this isn't the case, then `dnsmasq` simply ignores the request. So, in fact, I don't see an issue here. If you want to get this changed, then it must be changed withing `dnsmasq` itself.

If you find that `pihole-FTL` behaves any different from `dnsmasq` v2.79, you can re-open this issue.

**Comment by h2xtreme** [comment]
@DL6ER dnsmasq offers the setting to disable that behaviour. 

Just uncomment bind-interfaces in the /etc/dnsmasq.conf file and it will only try to bind in the interface that is set to listen. It won't user the wildcard.

Maybe something to be added to the 01-pihole.conf file?

**Comment by DL6ER** [comment]
How would you like to see this being added?
