### ISSUE TITLE
OSMC issues

### ISSUE THREAD

**Issue by technicalpyro** [pi-hole/FTL#27]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_{6}_

---

**[BUG | ISSUE] Expected Behaviour:**
FTL Operate correctly on OSMC and XBian

**[BUG | ISSUE] Actual Behaviour:**
https://discourse.pi-hole.net/t/pihole-ftl-refuses-to-start-after-upgrade-osmc/2895/12
seems to be failing to start

**[BUG | ISSUE] Steps to reproduce:**

-unsure what has changed in their installs
-
-
-

**Log file output [if available]**

`running debug now `

**Device specifics**

Hardware Type: rPi2B
OS: OSMC

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

I have spun up OSMC on my Pi2B and as f yet have not had any issues.  i will stand by for some troubleshooting on it if required and am willing to allow remote control through my firewall if that is easier

**Comment by dschaper** [comment]
Even powerusers and developers have to use the template :) Can you edit the post and put it back in for us?

**Comment by technicalpyro** [comment]
sure

**Comment by technicalpyro** [comment]
after full system upgrades and a couple reboots everything is running as it should e i will be stopping things to run the full debug process as listed in the README

**Comment by DL6ER** [comment]
I will close this issue as it is out-of-scope of `FTL`. We use the standard cross-compiler suite that is recommended for `armel` and `armhf` architectures. However, for some unknown reason, the dynamic linker, which is inevitably needed for running executables, is not in the correct (i.e. standard) location for the issues described on Discourse. Apparently, there exist specialized toolchains specifically tailored to these OSes.

Furthermore, given that
- Implementing these toolchains in our workflow (quality control and automated building of the binaries) seems extraordinary complicated
- Fixing this issue is as simple as putting the missing symlink into place,
- We don't even officially support those platforms

-> issue closed
