### ISSUE TITLE
pihole-FTL-arm-linux-gnueabi v4.0 binary isn't build for armel, but for armhf

### ISSUE THREAD

**Issue by rgerrits** [pi-hole/FTL#364]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

2

---

**[BUG | ISSUE] Expected Behaviour:**
Executing /usr/bin/pihole-FTL on an armel device that doesn't support armhf should start pihole-FTL proces

(/usr/bin/pihole-FTL being the file downloaded from https://github.com/pi-hole/FTL/releases/download/v4.0/pihole-FTL-arm-linux-gnueabi)

**[BUG | ISSUE] Actual Behaviour:**

It throws an error
bash: /usr/bin/pihole-FTL: No such file or directory

inspecting the file with readelf -l shows that it is requesting program interpreter: /lib/ld-linux-armhf.so.3

**[BUG | ISSUE] Steps to reproduce:**

- download https://github.com/pi-hole/FTL/releases/download/v4.0/pihole-FTL-arm-linux-gnueabi
- run  readelf -l pihole-FTL-arm-linux-gnueabi |grep interpreter
- see that the output is [Requesting program interpreter: /lib/ld-linux-armhf.so.3]
 (should be /lib/ld-linux.so.3 on armel devices)

**Log file output [if available]**

**Device specifics**

Hardware Type: ReadyNAS 104 ARM
OS: mostly debian jessie

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
We use the cross-compilers prepared by the Raspberry Pi foundation. The `arm-linux-gnuabi` binary is specifically compiled for the Raspberry Pi Zero and first generation (BCM2835, ARMv6). The default location for the interpreter is `/lib/ld-linux-armhf.so.3` on Raspbian.
A link `/lib/ld-linux-armhf.so.3` -> `/lib/ld-linux.so.3` *may* be sufficient for getting the binary work on your `armel` device (given at least an ARMv6 CPU).
If this doesn't help, you need to compile FTL locally on your device. This is a straightforward process and documented [here](https://docs.pi-hole.net/ftldns/compile/).

**Comment by rgerrits** [comment]
Created that symlink and tried it again -> now it segfaults
I already crosscompiled FTL for my device, apart from getting the correct version of nettle in my crosscompile environment, indeed pretty straightforward.

It was just that basic-install.sh lines 2150-2152 seems to suggest that pihole-FTL-arm-linux-gnueabi is build especially for plain armel.
So I expected it to work on my ARMv7l processor and assumed it was a bug in your build environment.

**Comment by DL6ER** [comment]
Okay, so we conclude that this is not a bug in our build environment, but rather a problem of a slightly unclear documentation/comments in the installer script:

https://github.com/pi-hole/pi-hole/blob/ddbdb51d209fa9eea2451a1bebfaeaef23a9b77b/automated%20install/basic-install.sh#L2150

Checking back with @Mcat12 if he thinks we should change this.
My opinion is that I don't think we should add a native `armel` build for mainly two reasons: (i) we have no device to test this on (at least no device that does not also support `hf` so we might miss something) and (ii) our list of officially supported platforms is intentionally such that we cover only the typical use cases. Otherwise, we would not be able to check support before releasing.
