### ISSUE TITLE
Support redirection

### ISSUE THREAD

**Issue by kuro68k** [pi-hole/FTL#428]
To aid blocking certain services it would be very helpful to support redirection.

For example, blocking YouTube ad domains breaks the YouTube app on many devices, especially smart TVs. The app keeps trying different servers to load a pre-roll ad, so the video never starts playing. One fix is to redirect the ad domains to another Google server that handles the request with a suitable response, but FTLDNS does not support this with regex matches.

**Comment by PromoFaux** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not fill out the Issue Template and do not provide debug tokens when possible. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

All Feature requests should be opened on [Discourse](https://discourse.pi-hole.net/c/feature-requests)
