### ISSUE TITLE
Feature Request: list on blockip in config

### ISSUE THREAD

**Issue by r00t0vi4** [pi-hole/FTL#442]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_8_

---

**[ISSUE] Expected Behaviour:**
pihole-FTL has a hardcoded IP-Addresses of block pages. I want to modify a list with own records without binary recompiling.
I introduse to add variables BLOCKPAGEIP and BLOCKPAGEIPV6 in pihole-FTL.conf with ip lists (example):

```
BLOCKPAGEIP=146.112.61.104,146.112.61.105,146.112.61.106,146.112.61.107
BLOCKPAGEIPV6=::ffff:146.112.61.104,::ffff:146.112.61.105
```

**Comment by DL6ER** [comment]
The hard-coded IPs are the IPs provided by the DNS resolvers we offer by default. You could also request to get more IPs added if, e.g., your ISP has its own set of addresses for the same purpose.

However, because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net), as mentioned in our [Issue Templates](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md).

Thank you for your understanding and best wishes for the holidays.
