### ISSUE TITLE
When using DHCP for IPv4 and IPv6, could we give out the same host ID?

### ISSUE THREAD

**Issue by mstum** [pi-hole/FTL#607]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_2_

---

**[ISSUE] Expected Behaviour:**

This is really a feature suggestion, not a bug/issue.

But if I use both IPv4 and IPv6 and use DHCP for both, I'd love to assign the same Host IP on both protocols. For example, if my IPv4 DHCP Range is 10.11.12.100-10.11.12.199 and my Pi-Hole has a static IPv6 address of `fdf7:77a4:2fcb:1234::2/64`, I'd love for DHCPv6 to assign either `fdf7:77a4:2fcb:1234::7B` or (preferably) `fdf7:77a4:2fcb:1234::123` to a host that gets assigned 10.11.12.123 via IPv4.

I am aware that IPv6 offers mechanisms like SLAAC, and that DNS Names are preferred. However, it is often convenient to know the IPv6 address of a host I know the IPv4 of (or vice-versa) because it's just a different prefix/notation. I'm also aware that the usual notations use decimal for IPv4 and hex for IPv6 and that the IPv6 version of .123 would be :7B, though as this is a user-friendliness feature, the incorrect notation of :123 seems the desirable one.

**[ISSUE] Actual Behaviour:**

DHCPv6 may assign a different IP (the actual Host part) than DHCPv4.

**[ISSUE] Steps to reproduce:**

- Configure a Pi-Hole host for both IPv4 and IPv6
- Setup DHCP and tick the IPv6 checkbox
- Request a DHCP Lease (e.g., `dhclient -v eth0` on Linux)
- Observe the assigned IPv4 and IPv6 addresses (e.g., `nmcli dev show eth0` on Ubuntu)

**Log file output [if available]**

N/A

**Device specifics**

N/A

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Some thoughts on this:

1. IPv6 really isn't like IPv4. This starts from that you should *not* use a central management instance for the configuration of an IPv6 network. Your post reads as if you might already be aware of this.
The ability to do the IP assignment standalone, i.e., without a DHCP server, is there for a reason. I personally think that the addition of a DHCP variant to the IPv6 standard was a mistake that helps people misunderstand how IPv6 is meant to work like. @dschaper might have a word or two on this as well.

2. You are asking for a few really counter-intuitive things like an automated translation `.123(dec) => :123(hex)`. I don't see this being valuable at all...

3. You say
    > I am aware that IPv6 offers mechanisms like SLAAC, and that DNS Names are preferred. 

    and this is very true. I'm working with dual-stack and IPv6-only networks since years and still believe that fixing the IP addresses of devices is almost always incorrect. The *only* devices that should have fixed IP addresses should be the gateway and the DNS server of your network. *Everything* else should be handled by properly set up host names via the DNS server. You might know that `10.0.3.132` is some server with a VPN gateway, but assume someone else looks at your configuration or even yourself after having been busy with other stuff for some time. If, instead of the IP address, you would have written the host name of this server, like `vpn-server-california.company`, it would be much more obvious and you don't have to memorize *any* IP addresses (gateway and DNS will be handled by the DHCP server).

4. Finally, I have to say that because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net), as mentioned in our [Issue Templates](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md).

Thank you for your understanding.
