### ISSUE TITLE
Some SRV Query Logs shown as action "N/A" .... but in log file as "NXDOMAIN" ... ?!?!

### ISSUE THREAD

**Issue by roe1974** [pi-hole/FTL#759]
Hi

Some SRV query are shown as Status "UNKNOWN(0)" and action "N/A" ... see picture:
<img width="746" alt="Unbenannt" src="https://user-images.githubusercontent.com/30420568/81684321-27dbc000-9457-11ea-976d-5e99a8afcdb9.PNG">

but in the pihole log it is a NXDOMAIN entry ....

May 12 13:37:29 dnsmasq[630]: query[SRV] _kerberos._tcp.Default-First-Site-Name._sites.dc._msdcs.INT.company.at from 192.168.xxx.xxx
May 12 13:37:29 dnsmasq[630]: cached _kerberos._tcp.Default-First-Site-Name._sites.dc._msdcs.INT.company.at is NXDOMAIN
May 12 13:37:29 dnsmasq[630]: query[SRV] _kerberos._tcp.dc._msdcs.INT.company.at from 192.168.xxx.xxx
May 12 13:37:29 dnsmasq[630]: cached _kerberos._tcp.dc._msdcs.INT.company.at is NXDOMAIN

This "problem" is since V5 ....

Richard

**Comment by roe1974** [comment]
here the samples:

<img width="749" alt="Unbenannt" src="https://user-images.githubusercontent.com/30420568/81843212-913dfa80-954d-11ea-9e62-4dbb78a396c4.PNG">
log:

May 13 18:59:33 dnsmasq[7298]: query[SRV] _kerberos._tcp.Default-First-Site-Name._sites.dc._msdcs.company.at from 192.168.xxx.xxx (src/dnsmasq/forward.c:1543)
May 13 18:59:33 dnsmasq[7298]: cached _kerberos._tcp.Default-First-Site-Name._sites.dc._msdcs.company.at is NXDOMAIN (src/dnsmasq/rfc1035.c:1942)
May 13 18:59:33 dnsmasq[7298]: query[SRV] _kerberos._tcp.dc._msdcs.company.at from 192.168.xxx.xxx (src/dnsmasq/forward.c:1543)
May 13 18:59:33 dnsmasq[7298]: cached _kerberos._tcp.dc._msdcs.company.at is NXDOMAIN (src/dnsmasq/rfc1035.c:1942)

<img width="748" alt="Unbenannt2" src="https://user-images.githubusercontent.com/30420568/81843240-9bf88f80-954d-11ea-87b0-b66d69227eca.PNG">

log:

May 13 19:02:03 dnsmasq[7298]: query[SRV] _ldap._tcp.Default-First-Site-Name._sites.dc._msdcs.company.at from 192.168.xxx.xxx (src/dnsmasq/forward.c:1543)
May 13 19:02:03 dnsmasq[7298]: cached _ldap._tcp.Default-First-Site-Name._sites.dc._msdcs.company.at is NXDOMAIN (src/dnsmasq/rfc1035.c:1942)
May 13 19:02:03 dnsmasq[7298]: query[SRV] _ldap._tcp.dc._msdcs.company.at from 192.168.xxx.xxx (src/dnsmasq/forward.c:1543)
May 13 19:02:03 dnsmasq[7298]: cached _ldap._tcp.dc._msdcs.company.at is NXDOMAIN (src/dnsmasq/rfc1035.c:1942)
May 13 19:02:03 dnsmasq[7298]: query[SRV] _ldap._tcp.2a486595-2abb-4f07-b026-0884c31e2c35.domains._msdcs.company.at from 192.168.xxx.xxx (src/dnsmasq/forward.c:1543)
May 13 19:02:03 dnsmasq[7298]: cached _ldap._tcp.2a486595-2abb-4f07-b026-0884c31e2c35.domains._msdcs.company.at is NXDOMAIN (src/dnsmasq/rfc1035.c:1942)

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/komisches-blocken-typ-srv-komische-domane-etc/32308/3

**Comment by yubiuser** [comment]
https://discourse.pi-hole.net/t/komisches-blocken-typ-srv-komische-domane-etc/32308

**Comment by roe1974** [comment]
another interesting query / log entry:
<img width="735" alt="Unbenannt" src="https://user-images.githubusercontent.com/30420568/81949183-d96b2480-9602-11ea-8e45-6bdcb281fe5d.PNG">
log:
May 14 16:27:05 dnsmasq[615]: query[SRV] _http._tcp.raspbian.raspberrypi.org from 192.168.xxx.xxx
May 14 16:27:05 dnsmasq[615]: cached _http._tcp.raspbian.raspberrypi.org is NODATA

a little bit later ......
<img width="731" alt="Unbenannt2" src="https://user-images.githubusercontent.com/30420568/81949307-fd2e6a80-9602-11ea-976f-c291e8431dc9.PNG">
log:
May 14 06:35:02 dnsmasq[615]: query[SRV] _http._tcp.raspbian.raspberrypi.org from 192.168.xxx.xxx
May 14 06:35:02 dnsmasq[615]: forwarded _http._tcp.raspbian.raspberrypi.org to 1.1.1.1

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-v5-0-query-log-shows-status-unknown-9-since-having-upgraded-from-v4-4/32386/14

**Comment by DL6ER** [comment]
@roe1974 Why is the extra `(src/dnsmasq/rfc1035.c:1942)` output missing in your last post? Did you disable this again?

**Comment by DL6ER** [comment]
Ah, never mind, I found what is causing this. `dnsmasq` v2.81 (embedded in Pi-hole FTL v5.0) adds the ability to cache SRV records. FTL should analyze them as well.

@roe1974 Please try whether
```
pihole checkout ftl fix/process_SRV_cache_master
```
fixes this for you.

For the record: This bug was introduced in https://github.com/pi-hole/FTL/commit/6631fde1d984e89ac68897b72c56cd9db06960d8

**Comment by roe1974** [comment]
@DL6ER ... sorry the last example was from my secondary Pi-Hole DNS ... there was no debug activated ¯\_(ツ)_/¯
... and just a short question:

pihole checkout ftl fix/process_SRV_cache_master

... i a ssh comand ?

Richard

**Comment by DL6ER** [comment]
@roe1974 Yes, connect to your Pi-hole via ssh can run the command. Confirm the warning and the rest will happen automatically.

**Comment by roe1974** [comment]
@DL6ER ok, and what is the comand doing ;-) ?

**Comment by yubiuser** [comment]
It will let you try out a testing brach of pihole's dns engine where DL fixed some things.
What it does in detail you can see here: https://github.com/pi-hole/FTL/commit/237c70d76db25cd9bbc12887e07ce221ff0213ce

**Comment by roe1974** [comment]
sorryfor the late answer ... works now with this "patch" 
thx !
Richard

**Comment by lesthawk** [comment]
I had the same issue, tried the fix and it works here too, so that looks like two confirmed separate reports with the fix being a viable solution.... how long before we can get the official full version including this fix?

**Comment by lesthawk** [comment]
scratch the last comment, rebooted all  the devices and the problem is back....

**Comment by DL6ER** [comment]
@lesthawk What are the corresponding log lines in `/var/log/pihole.log`? And what is the output of `pihole -v`?

**Comment by lesthawk** [comment]
> @lesthawk What are the corresponding log lines in `/var/log/pihole.log`? And what is the output of `pihole -v`?

latest version installed again at the moment but i ran the version at the time using:
pihole checkout ftl fix/process_SRV_cache_master
and confirmed it was the branch version.
I've since worked around the issue by using the local network pc forwarding dns lookup usually reserved for the router, to link back to the DC (which is currently running a Samba internal dns) however this has it's own forwarder set to the Pihole DNS so I'm concerned about locally looping.

If I installed Bind 9 on a dummy nic and referenced that by the Samba-tool domain provision AND PIHole then would this resolve all the issues? If so, it could be worth registering this as a ferature request to combine pi-hole with a Samba-Tool DC with a Bind9 BackEnd?

re the branch, as I said it failed, so I worked around the issue, but it's easily replicable on a system configured with a  basic Sama-tool DC using Samba Internal DNS

**Comment by DL6ER** [comment]
This is a sole displaying issue here. The underlying DNS machinery works just as you expect it to, so I'm not quite getting what you need to work around to get proper function here?

**Comment by lesthawk** [comment]
Effectively I’m trying to get pihole to return the SVR records. I’ve found a rough workaround involving pihole using a Bind9 DNS as the upstream DNS, itself running on a separate virtual adaptor of eth53.
I’m working out the kinks of this as the samba AD DC has to ignore the pihole and connect directly to the Bind9. This is all so that PIhole can act as the dhcp server and not just the ad block upstream DNS, ie it is the main network DNS.

This may look like a complicated setup but it’s an all too real situation I’m looking to resolve. Whilst I’m trying to have Pihole happily coexist on the same box as the DC, which I don’t think this is uncommon, the issue would just as easily occur if pihole were on another box. Issue seems to be it acts a tad flakey returning SVR records even when the upstream DNS is a local network DNS such as Bind9.

Sent from my iPhone

On 22 May 2020, at 22:56, DL6ER <notifications@github.com> wrote:

﻿

This is a sole displaying issue here. The underlying DNS machinery works just as you expect it to, so I'm not quite getting what you need to work around to get proper function here?
