### ISSUE TITLE
doesn't build with clang/llvm/etc

### ISSUE THREAD

**Issue by tomsparks** [pi-hole/FTL#768]
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**
1

---

**[BUG | ISSUE] Expected Behaviour:**

code compiles

**[BUG | ISSUE] Actual Behaviour:**

code doesn't check for compiler type
code fails to compile because it expects GCC

**[BUG | ISSUE] Steps to reproduce:**

type gmake in FTL directory

**Log file output [if available]**

% gmake
cc -c -o build/database/common.o src/database/common.c -g3 -std=gnu11 -pipe -Isrc -Wall -Wextra -Wno-unused-parameter -D_FILE_OFFSET_BITS=64 -fstack-protector-strong -Wp,-D_FORTIFY_SOURCE=2 -O3 -Wl,-z,relro,-z,now -fexceptions -funwind-tables -fasynchronous-unwind-tables -Wl,-z,defs -Wl,-z,now -Wl,-z,relro -pie -fPIE -rdynamic -fno-omit-frame-pointer  -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_DEFAULT_MEMSTATUS=0 -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_PROGRESS_CALLBACK -DSQLITE_OMIT_MEMORYDB -DSQLITE_DEFAULT_FOREIGN_KEYS=1 -DSQLITE_DQS=0 -DHAVE_POLL_H -Werror -Waddress -Wlogical-op -Wmissing-field-initializers -Woverlength-strings -Wformat -Wformat-nonliteral -Wuninitialized -Wswitch-enum -Wshadow -Wfloat-equal -Wbad-function-cast -Wwrite-strings -Wparentheses -Wlogical-op -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Winline 
cc: error: -Wl,-z,relro,-z,now: 'linker' input unused [-Werror,-Wunused-command-line-argument]
cc: error: -Wl,-z,defs: 'linker' input unused [-Werror,-Wunused-command-line-argument]
cc: error: -Wl,-z,now: 'linker' input unused [-Werror,-Wunused-command-line-argument]
cc: error: -Wl,-z,relro: 'linker' input unused [-Werror,-Wunused-command-line-argument]
gmake: *** [Makefile:137: build/database/common.o] Error 1

**Device specifics**

Hardware Type: Lenovo T530
OS: FreeBSD 12.1

**Comment by DL6ER** [comment]
Pi-hole was developed for Raspberry Pis, initially. The traditional cross-compiler (we obviously want to cross-compile from x86_64 machines in a CI environment) is the `gcc` compiler.

There is no specific reason for why we support one and not the other, we just never tried `clang`. You are invited to submit a pull request to our project if this does not make the Makefile unusable. I don't think we should go the way of including a `configure` script.

Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net), as mentioned in our [Issue Templates](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md).

Thank you for your understanding.
