### ISSUE TITLE
pihole-FTL size

### ISSUE THREAD

**Issue by laoshaw** [pi-hole/FTL#929]
the newest pihole-FTL binary size is 10M before strip, it's 2MB after strip, still this is much larger than dnsmasq which is normally <500KB insize, what made pihole-FTL so much bigger?

**Comment by dschaper** [comment]
You're looking at the source code, figure it out.

**Comment by DL6ER** [comment]
> what made pihole-FTL so much bigger

Well, the major difference is that FTL includes **a fully-fledged SQLIte3 database engine**. In addition, there will be **a standalone LUA interpreter**, our own, more capable, **regex engine**. In the more distant future, FTL will contain its **own web server** and dynamic **PHP interpreter**.

This all requires quite some space and is needed to ensure Pi-hole works reliably and that we can expect the same version on every device to ease maintainability. You'll understand that maintainability is key for a small project with only volunteers working on it so we can concentrate on writing new features instead of trying to fix incompatibilities because users depend on script/database engines ranging from anywhere between 2015 to 2020.

As an example, look at https://discourse.pi-hole.net/t/adding-alias-clients-to-pi-hole-ftl/37084/98?u=dl6er
Here you can see the command which is possible with a recent SQLIte3 database engine (which is bundled into FTL). But you can see also what is needed on a raspberry Pi featuring a much older database engine (click the hidden info to get it). It should be clear what is easier to maintain.

**Comment by dschaper** [comment]
If you're still trying to get [Pi-hole in 64M of space](https://github.com/pi-hole/FTL/issues/904) then my advice is the same as last time.
