### ISSUE TITLE
FTL crashed immediately after starting

### ISSUE THREAD

**Issue by nicnau** [pi-hole/FTL#975]
### Versions

- Pi-hole:  5.2.1
- AdminLTE:  5.2.1
- FTL:  5.3.2

### Platform

- OS and version:  Debian GNU/Linux 10 (buster)

- Platform:  Raspberry Pi 4

### Expected behavior

FTL starts and provides DNS.

### Actual behavior / bug

When starting FTL via WebUI it immediately crashes.

### Steps to reproduce

1. Go to pi.hole:8088
2. Click on Enable -> DNS shows running
3. Reload page -> DNS shows not running

## Debug Token

- URL:  https://tricorder.pi-hole.net/q1z68yya32

### Additional context

Maybe this is relevant (can also be seen from log): I also use the Pi to run Nextcloud/NextCloudPi and Duplicati with WebUIs. Thus the different port for the pihole webui.

**Comment by dschaper** [comment]
You're running Apache2, you'll need to open a support issue on the Community Support section of https://discourse.pi-hole.net.

**Comment by dschaper** [comment]
If you are Experiencing issues with a Pi-hole install that has non-standard elements (e.g you are using nginx instead of lighttpd, or there is some other aspect of your install that is customised) - please use the [Community Help](https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36) category.

**Comment by nicnau** [comment]
I see, thanks. It seems to be more involed than I initially hoped. I will have to revisit this later.
